name: Daily WakaTime Logger

on:
  schedule:
    - cron: "12 * * * *"   # At minute 5 past every hour
  workflow_dispatch:
    inputs:
      manual_minutes:
        description: "Manual work time in minutes"
        required: false
        default: "0"

jobs:
  log-activity:
    runs-on: ubuntu-latest

    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run the log script
        run: python daily_log.py ${{ github.event.inputs.manual_minutes || '0' }}

      - name: Configure git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Show git status
        run: git status

      - name: Show recent commits
        run: git log -3 --oneline

      - name: Push commits (if any)
        run: |
          git pull --rebase
          git push
